---
# handlers file for snmp
- name: stop snmpd
  service:
    name: snmpd
    state: stopped 

- name: start snmpd
  service:
    name: snmpd
    state: started

- name: enable snmpd
  service:
    name: snmpd
    enabled: yes

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

